# Generated by Django 4.2.9 on 2024-01-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.FloatField(default=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='banner',
            field=models.ImageField(upload_to='course'),
        ),
    ]
